#pragma once
#include <iostream>
#include "Connection.h"


enum class ServerToClientHeaders
{
	SEND_ID = 0,
	SEND_TEXT,
	SEND_CLIENT_COLOR,
	SEND_ALL_CLIENT_COLORS,
	SEND_CLIENT_CURSOR_POS,
	SEND_SELECTION_DATA,
	SERVER_REMOVE_SELECTION,
	SERVER_REMOVE_CHAR,
	CLIENT_END,
	SERVER_END
};

